name: coolmovies
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
   sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_screenutil: ^5.9.1
  get_it: ^7.7.0
  go_router: ^14.1.2
  graphql_flutter: ^5.1.2
  logger: ^2.3.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Light.ttf
          weight: 300
        - asset: assets/fonts/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ExtraLight.ttf
          weight: 100


  assets:
    - assets/fonts/

