name: coolmovies
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
   sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_screenutil: ^5.9.1
  get_it: ^7.7.0
  go_router: ^14.1.2
  graphql_flutter: ^5.1.2
  logger: ^2.3.0
  provider: 
  skeletonizer: ^1.1.1
  shared_preferences: ^2.0.15
  retrofit: ^4.0.3

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  json_serializable:
  mockito:
  retrofit_generator: ^7.0.1
  flutter_test:
    sdk: flutter
flutter_gen:
  output: lib/common/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: CoolMoviesAssets
      package_parameter_enabled: false
  fonts:
    outputs:
      class_name: CoolMoviesFonts
      package_parameter_enabled: true



flutter:

  uses-material-design: true
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Light.ttf
          weight: 300
        - asset: assets/fonts/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ExtraLight.ttf
          weight: 100


  assets:
    - assets/fonts/

